### ISSUE TITLE
Fix ownership on /rails

### ISSUE THREAD

**Issue by judu** [gemnasium/rails-meets-docker#2]
I quite liked your blog post about an "almost real life" Dockerfile.

However, I tried it, and it turns out that the /setup script won't work unless you chown the /rails folder:
I'm too lazy to make a proper pull request, so I'm just dropping it here:

RUN chown rails -R /rails

I had to put that just after the "ADD … /rails" instruction.

**Comment by gravis** [comment]
Thanks for pointing this!
